import type { Locale } from './i18n';
import type { FieldDefinition } from './recorders';

const descriptions = {
  "zh-CN": {
    "score": "根据字段值及其可调整的权重计算。",
    "lastUpdatedAt": "最近一次核实该产品信息的日期。",
    "lastUpdatedVersion": "最近一次信息更新对应的应用版本。",
    "technologyApproach": "选择预设技术方案，或输入其他实现方式。",
    "supportsIntelMac": "可在搭载 Intel 芯片的 Mac 上运行。",
    "appSizeMB": "应用安装后占用的磁盘空间，单位为 MB，不是安装包或下载文件的大小。",
    "supportsCli": "可通过终端调用。",
    "supportsMcp": "提供 MCP 服务器，供本地智能体集成。",
    "supportsBuiltInAgent": "应用内直接提供 AI 智能体。",
    "monthlyPrice": "以美元计价；如不提供该选项，请留空。",
    "quarterlyPrice": "以美元计价，每三个月收费一次。",
    "yearlyPrice": "以美元计价，按年收费。",
    "supportsScreenshotCapture": "支持截取屏幕画面。",
    "supportsScreenshots": "支持截取指定应用窗口。",
    "supportsScrollingScreenshots": "可将超出可视区域的内容截取为一张连续图片。",
    "supportsCopyText": "支持识别并复制截图中的文字。",
    "supportsCustomBackgrounds": "支持自定义录屏或截图的背景。",
    "supportsCustomCorners": "支持调整画面的圆角。",
    "supportsCustomShadows": "支持自定义画面阴影。",
    "supports3DEffects": "支持透视或三维展示效果。",
    "supportsDeviceFrames": "可将录屏或截图放入设备模型中展示。",
    "supportsResolutionControls": "支持调整输出分辨率或图像清晰度。",
    "zoomLimit": "支持的最大缩放倍数。",
    "supportsCameraLayouts": "支持基本画中画以外的摄像头布局，例如左右并排或上下排列。",
    "supportsCameraLayoutAnimations": "支持摄像头布局之间的动画过渡。",
    "supportsAnnotationOverlay": "支持同时叠加多个元素。",
    "supportsCustomCursorStyle": "可使用自行上传的素材、技能生成的样式包或其他自定义光标资源。",
    "supportsPresetImportExportSharing": "可将预设导出为 Finder 中可见的本地文件，并支持导入预设文件。",
    "lifetimePrice": "以美元计价；如不提供该选项，请留空。"
  },
  "zh-TW": {
    "score": "根據欄位值及其可調整的權重計算。",
    "lastUpdatedAt": "最近一次核實該產品資訊的日期。",
    "lastUpdatedVersion": "最近一次資訊更新對應的應用程式版本。",
    "technologyApproach": "選擇預設技術方案，或輸入其他實作方式。",
    "supportsIntelMac": "可在搭載 Intel 晶片的 Mac 上執行。",
    "appSizeMB": "應用程式安裝後佔用的磁碟空間，單位為 MB，並非安裝包或下載檔案的大小。",
    "supportsCli": "可透過終端機呼叫。",
    "supportsMcp": "提供 MCP 伺服器，供本機 AI 代理整合。",
    "supportsBuiltInAgent": "應用程式內直接提供 AI 代理。",
    "monthlyPrice": "以美元計價；如不提供該選項，請留空。",
    "quarterlyPrice": "以美元計價，每三個月收費一次。",
    "yearlyPrice": "以美元計價，按年收費。",
    "supportsScreenshotCapture": "支援擷取螢幕畫面。",
    "supportsScreenshots": "支援擷取指定應用程式視窗。",
    "supportsScrollingScreenshots": "可將超出可視區域的內容擷取為一張連續圖片。",
    "supportsCopyText": "支援辨識並複製截圖中的文字。",
    "supportsCustomBackgrounds": "支援自訂錄影或截圖的背景。",
    "supportsCustomCorners": "支援調整畫面的圓角。",
    "supportsCustomShadows": "支援自訂畫面陰影。",
    "supports3DEffects": "支援透視或三維展示效果。",
    "supportsDeviceFrames": "可將錄影或截圖放入裝置模型中展示。",
    "supportsResolutionControls": "支援調整輸出解析度或影像清晰度。",
    "zoomLimit": "支援的最大縮放倍率。",
    "supportsCameraLayouts": "支援基本子母畫面以外的攝影機版面，例如左右並排或上下排列。",
    "supportsCameraLayoutAnimations": "支援攝影機版面之間的動畫轉場。",
    "supportsAnnotationOverlay": "支援同時疊加多個元素。",
    "supportsCustomCursorStyle": "可使用自行上傳的素材、技能產生的樣式包或其他自訂游標資源。",
    "supportsPresetImportExportSharing": "可將預設匯出為 Finder 中可見的本機檔案，並支援匯入預設檔案。",
    "lifetimePrice": "以美元計價；如不提供該選項，請留空。"
  },
  "ja": {
    "score": "各項目の値と調整可能な重みから算出します。",
    "lastUpdatedAt": "製品情報を最後に確認した日付です。",
    "lastUpdatedVersion": "情報の最終更新時点のアプリバージョンです。",
    "technologyApproach": "既定の技術を選択するか、別の実装方式を入力します。",
    "supportsIntelMac": "Intel搭載Macで動作します。",
    "appSizeMB": "インストール済みアプリが使用するディスク容量（MB）です。インストーラーやダウンロードのサイズではありません。",
    "supportsCli": "ターミナルから実行できます。",
    "supportsMcp": "ローカルエージェントと連携するMCPサーバーを提供します。",
    "supportsBuiltInAgent": "アプリ内にAIエージェントを搭載しています。",
    "monthlyPrice": "米ドル表記です。利用できない場合は空欄にしてください。",
    "quarterlyPrice": "米ドルで3か月ごとに請求されます。",
    "yearlyPrice": "米ドルで毎年請求されます。",
    "supportsScreenshotCapture": "スクリーンショットを撮影できます。",
    "supportsScreenshots": "特定のアプリウィンドウを撮影できます。",
    "supportsScrollingScreenshots": "表示範囲を超える内容を1枚の連続した画像として撮影できます。",
    "supportsCopyText": "スクリーンショット内の文字を認識してコピーできます。",
    "supportsCustomBackgrounds": "録画やスクリーンショットの背景を変更できます。",
    "supportsCustomCorners": "画像の角の丸みを調整できます。",
    "supportsCustomShadows": "画像の影を調整できます。",
    "supports3DEffects": "遠近感や立体的な表示効果に対応しています。",
    "supportsDeviceFrames": "録画やスクリーンショットをデバイスのモックアップ内に配置できます。",
    "supportsResolutionControls": "出力解像度や画像の鮮明さを調整できます。",
    "zoomLimit": "対応する最大ズーム倍率です。",
    "supportsCameraLayouts": "基本的なピクチャーインピクチャーに加え、左右や上下に並べるカメラレイアウトに対応しています。",
    "supportsCameraLayoutAnimations": "カメラレイアウトの切り替えをアニメーション化できます。",
    "supportsAnnotationOverlay": "複数の要素を同時に重ねて表示できます。",
    "supportsCustomCursorStyle": "アップロードした素材、スキルで生成したパックなどのカスタムカーソル素材を使用できます。",
    "supportsPresetImportExportSharing": "プリセットをFinderで確認できるローカルファイルとして書き出し、プリセットファイルを読み込めます。",
    "lifetimePrice": "米ドル表記です。利用できない場合は空欄にしてください。"
  },
  "ko": {
    "score": "필드 값과 조정 가능한 가중치로 계산합니다.",
    "lastUpdatedAt": "제품 정보를 마지막으로 확인한 날짜입니다.",
    "lastUpdatedVersion": "정보를 마지막으로 업데이트했을 때의 앱 버전입니다.",
    "technologyApproach": "기본 기술을 선택하거나 다른 구현 방식을 입력하세요.",
    "supportsIntelMac": "Intel 기반 Mac에서 실행할 수 있습니다.",
    "appSizeMB": "설치된 앱이 차지하는 디스크 공간(MB)입니다. 설치 파일이나 다운로드 크기가 아닙니다.",
    "supportsCli": "터미널에서 호출할 수 있습니다.",
    "supportsMcp": "로컬 에이전트 연동을 위한 MCP 서버를 제공합니다.",
    "supportsBuiltInAgent": "앱 내에서 AI 에이전트를 직접 제공합니다.",
    "monthlyPrice": "미국 달러 기준입니다. 제공되지 않으면 비워 두세요.",
    "quarterlyPrice": "미국 달러로 3개월마다 청구됩니다.",
    "yearlyPrice": "미국 달러로 매년 청구됩니다.",
    "supportsScreenshotCapture": "스크린샷을 촬영할 수 있습니다.",
    "supportsScreenshots": "특정 앱 창을 캡처할 수 있습니다.",
    "supportsScrollingScreenshots": "화면 밖의 내용까지 하나의 연속된 이미지로 캡처할 수 있습니다.",
    "supportsCopyText": "스크린샷의 텍스트를 인식하고 복사할 수 있습니다.",
    "supportsCustomBackgrounds": "녹화 또는 스크린샷의 배경을 사용자 지정할 수 있습니다.",
    "supportsCustomCorners": "화면 모서리의 둥글기를 조절할 수 있습니다.",
    "supportsCustomShadows": "화면 그림자를 사용자 지정할 수 있습니다.",
    "supports3DEffects": "원근 또는 3D 표현 효과를 지원합니다.",
    "supportsDeviceFrames": "녹화 또는 스크린샷을 기기 목업 안에 배치할 수 있습니다.",
    "supportsResolutionControls": "출력 해상도나 이미지 선명도를 조절할 수 있습니다.",
    "zoomLimit": "지원하는 최대 확대 배율입니다.",
    "supportsCameraLayouts": "기본 화면 속 화면 외에 좌우 또는 상하 배치 등의 카메라 레이아웃을 지원합니다.",
    "supportsCameraLayoutAnimations": "카메라 레이아웃 전환에 애니메이션을 적용할 수 있습니다.",
    "supportsAnnotationOverlay": "여러 요소를 동시에 오버레이할 수 있습니다.",
    "supportsCustomCursorStyle": "직접 업로드한 에셋, 스킬로 생성한 팩 또는 기타 사용자 지정 커서 리소스를 사용할 수 있습니다.",
    "supportsPresetImportExportSharing": "프리셋을 Finder에서 볼 수 있는 로컬 파일로 내보내고 프리셋 파일을 가져올 수 있습니다.",
    "lifetimePrice": "미국 달러 기준입니다. 제공되지 않으면 비워 두세요."
  },
  "es": {
    "score": "Se calcula a partir de los valores y sus pesos ajustables.",
    "lastUpdatedAt": "Fecha de la última verificación de la información del producto.",
    "lastUpdatedVersion": "Versión de la aplicación correspondiente a la última actualización de la información.",
    "technologyApproach": "Elige una tecnología predefinida o introduce otra implementación.",
    "supportsIntelMac": "Puede ejecutarse en Mac con procesador Intel.",
    "appSizeMB": "Espacio en disco de la aplicación instalada, en MB; no es el tamaño del instalador ni de la descarga.",
    "supportsCli": "Se puede invocar desde un terminal.",
    "supportsMcp": "Ofrece un servidor MCP para integrar agentes locales.",
    "supportsBuiltInAgent": "Incluye un agente de IA en la aplicación.",
    "monthlyPrice": "En dólares estadounidenses. Déjalo vacío si no está disponible.",
    "quarterlyPrice": "En dólares estadounidenses, facturado cada tres meses.",
    "yearlyPrice": "En dólares estadounidenses, facturado anualmente.",
    "supportsScreenshotCapture": "Puede tomar capturas de pantalla.",
    "supportsScreenshots": "Puede capturar una ventana específica de una aplicación.",
    "supportsScrollingScreenshots": "Puede capturar contenido fuera del área visible en una sola imagen continua.",
    "supportsCopyText": "Puede reconocer y copiar texto de una captura de pantalla.",
    "supportsCustomBackgrounds": "Puede personalizar el fondo de grabaciones o capturas de pantalla.",
    "supportsCustomCorners": "Puede ajustar el redondeo de las esquinas de la imagen.",
    "supportsCustomShadows": "Puede personalizar las sombras de la imagen.",
    "supports3DEffects": "Admite efectos de perspectiva o presentación tridimensional.",
    "supportsDeviceFrames": "Puede colocar grabaciones o capturas dentro de maquetas de dispositivos.",
    "supportsResolutionControls": "Puede ajustar la resolución de salida o la nitidez de la imagen.",
    "zoomLimit": "Multiplicador de zoom máximo admitido.",
    "supportsCameraLayouts": "Admite diseños de cámara más allá de la imagen en imagen, como lado a lado o arriba y abajo.",
    "supportsCameraLayoutAnimations": "Puede animar las transiciones entre diseños de cámara.",
    "supportsAnnotationOverlay": "Admite varias superposiciones al mismo tiempo.",
    "supportsCustomCursorStyle": "Puede usar recursos subidos por el usuario, paquetes generados con habilidades u otros recursos de cursor personalizados.",
    "supportsPresetImportExportSharing": "Puede exportar ajustes preestablecidos como archivos locales visibles en Finder e importar archivos de ajustes.",
    "lifetimePrice": "En dólares estadounidenses. Déjalo vacío si no está disponible."
  },
  "fr": {
    "score": "Calculé à partir des valeurs des champs et de leurs poids réglables.",
    "lastUpdatedAt": "Date de la dernière vérification des informations du produit.",
    "lastUpdatedVersion": "Version de l’application correspondant à la dernière mise à jour des informations.",
    "technologyApproach": "Choisissez une technologie prédéfinie ou indiquez une autre méthode d’implémentation.",
    "supportsIntelMac": "Peut fonctionner sur les Mac équipés d’un processeur Intel.",
    "appSizeMB": "Espace disque occupé par l’application installée, en Mo, et non la taille du programme d’installation ou du téléchargement.",
    "supportsCli": "Peut être appelé depuis un terminal.",
    "supportsMcp": "Fournit un serveur MCP pour l’intégration d’agents locaux.",
    "supportsBuiltInAgent": "Intègre un agent IA directement dans l’application.",
    "monthlyPrice": "En dollars américains. Laissez vide si cette option n’est pas disponible.",
    "quarterlyPrice": "En dollars américains, facturés tous les trois mois.",
    "yearlyPrice": "En dollars américains, facturés annuellement.",
    "supportsScreenshotCapture": "Permet de prendre des captures d’écran.",
    "supportsScreenshots": "Permet de capturer une fenêtre d’application précise.",
    "supportsScrollingScreenshots": "Permet de capturer le contenu au-delà de la zone visible en une seule image continue.",
    "supportsCopyText": "Permet de reconnaître et de copier le texte d’une capture d’écran.",
    "supportsCustomBackgrounds": "Permet de personnaliser l’arrière-plan des enregistrements ou captures d’écran.",
    "supportsCustomCorners": "Permet de régler l’arrondi des coins de l’image.",
    "supportsCustomShadows": "Permet de personnaliser les ombres de l’image.",
    "supports3DEffects": "Prend en charge les effets de perspective ou de présentation en trois dimensions.",
    "supportsDeviceFrames": "Permet de placer les enregistrements ou captures dans des maquettes d’appareils.",
    "supportsResolutionControls": "Permet de régler la résolution de sortie ou la netteté de l’image.",
    "zoomLimit": "Facteur de zoom maximal pris en charge.",
    "supportsCameraLayouts": "Propose des dispositions de caméra autres que l’incrustation classique, comme côte à côte ou superposées verticalement.",
    "supportsCameraLayoutAnimations": "Permet d’animer les transitions entre les dispositions de caméra.",
    "supportsAnnotationOverlay": "Prend en charge plusieurs éléments superposés simultanément.",
    "supportsCustomCursorStyle": "Permet d’utiliser des ressources importées, des packs générés par des compétences ou d’autres ressources de curseur personnalisées.",
    "supportsPresetImportExportSharing": "Permet d’exporter les préréglages en fichiers locaux visibles dans le Finder et d’importer des fichiers de préréglages.",
    "lifetimePrice": "En dollars américains. Laissez vide si cette option n’est pas disponible."
  },
  "de": {
    "score": "Wird aus Feldwerten und ihren einstellbaren Gewichtungen berechnet.",
    "lastUpdatedAt": "Datum der letzten Überprüfung der Produktinformationen.",
    "lastUpdatedVersion": "App-Version zum Zeitpunkt der letzten Informationsaktualisierung.",
    "technologyApproach": "Voreingestellte Technologie auswählen oder eine andere Implementierung eingeben.",
    "supportsIntelMac": "Kann auf Intel-basierten Macs ausgeführt werden.",
    "appSizeMB": "Speicherplatz der installierten App in MB, nicht die Größe des Installationsprogramms oder Downloads.",
    "supportsCli": "Kann über ein Terminal aufgerufen werden.",
    "supportsMcp": "Bietet einen MCP-Server zur Integration lokaler Agenten.",
    "supportsBuiltInAgent": "Bietet einen KI-Agenten direkt in der App.",
    "monthlyPrice": "In US-Dollar. Leer lassen, wenn nicht verfügbar.",
    "quarterlyPrice": "In US-Dollar, Abrechnung alle drei Monate.",
    "yearlyPrice": "In US-Dollar, jährliche Abrechnung.",
    "supportsScreenshotCapture": "Kann Screenshots aufnehmen.",
    "supportsScreenshots": "Kann ein bestimmtes App-Fenster aufnehmen.",
    "supportsScrollingScreenshots": "Kann Inhalte außerhalb des sichtbaren Bereichs als ein durchgehendes Bild aufnehmen.",
    "supportsCopyText": "Kann Text in Screenshots erkennen und kopieren.",
    "supportsCustomBackgrounds": "Kann den Hintergrund von Aufnahmen oder Screenshots anpassen.",
    "supportsCustomCorners": "Kann die Rundung der Bildecken anpassen.",
    "supportsCustomShadows": "Kann Bildschatten anpassen.",
    "supports3DEffects": "Unterstützt Perspektiv- oder dreidimensionale Darstellungseffekte.",
    "supportsDeviceFrames": "Kann Aufnahmen oder Screenshots in Gerätemodelle einfügen.",
    "supportsResolutionControls": "Kann die Ausgabeauflösung oder Bildschärfe anpassen.",
    "zoomLimit": "Maximal unterstützter Zoomfaktor.",
    "supportsCameraLayouts": "Unterstützt neben einfachem Bild-in-Bild auch Kameralayouts nebeneinander oder übereinander.",
    "supportsCameraLayoutAnimations": "Kann Übergänge zwischen Kameralayouts animieren.",
    "supportsAnnotationOverlay": "Unterstützt mehrere gleichzeitige Überlagerungen.",
    "supportsCustomCursorStyle": "Kann hochgeladene Dateien, durch Skills erzeugte Pakete oder andere eigene Cursor-Ressourcen verwenden.",
    "supportsPresetImportExportSharing": "Kann Voreinstellungen als lokale, im Finder sichtbare Dateien exportieren und Voreinstellungsdateien importieren.",
    "lifetimePrice": "In US-Dollar. Leer lassen, wenn nicht verfügbar."
  },
  "pt-BR": {
    "score": "Calculado a partir dos valores dos campos e seus pesos ajustáveis.",
    "lastUpdatedAt": "Data da última verificação das informações do produto.",
    "lastUpdatedVersion": "Versão do aplicativo correspondente à última atualização das informações.",
    "technologyApproach": "Escolha uma tecnologia predefinida ou informe outra forma de implementação.",
    "supportsIntelMac": "Pode ser executado em Macs com processador Intel.",
    "appSizeMB": "Espaço em disco ocupado pelo aplicativo instalado, em MB, não o tamanho do instalador ou do download.",
    "supportsCli": "Pode ser executado pelo terminal.",
    "supportsMcp": "Oferece um servidor MCP para integração com agentes locais.",
    "supportsBuiltInAgent": "Inclui um agente de IA diretamente no aplicativo.",
    "monthlyPrice": "Em dólares americanos. Deixe em branco se não estiver disponível.",
    "quarterlyPrice": "Em dólares americanos, cobrados a cada três meses.",
    "yearlyPrice": "Em dólares americanos, cobrados anualmente.",
    "supportsScreenshotCapture": "Permite capturar a tela.",
    "supportsScreenshots": "Permite capturar uma janela específica de um aplicativo.",
    "supportsScrollingScreenshots": "Permite capturar conteúdo além da área visível em uma única imagem contínua.",
    "supportsCopyText": "Permite reconhecer e copiar texto de uma captura de tela.",
    "supportsCustomBackgrounds": "Permite personalizar o fundo de gravações ou capturas de tela.",
    "supportsCustomCorners": "Permite ajustar o arredondamento dos cantos da imagem.",
    "supportsCustomShadows": "Permite personalizar as sombras da imagem.",
    "supports3DEffects": "Oferece efeitos de perspectiva ou apresentação tridimensional.",
    "supportsDeviceFrames": "Permite inserir gravações ou capturas em modelos de dispositivos.",
    "supportsResolutionControls": "Permite ajustar a resolução de saída ou a nitidez da imagem.",
    "zoomLimit": "Fator máximo de zoom suportado.",
    "supportsCameraLayouts": "Oferece layouts de câmera além do picture-in-picture básico, como lado a lado ou um acima do outro.",
    "supportsCameraLayoutAnimations": "Permite animar transições entre layouts de câmera.",
    "supportsAnnotationOverlay": "Oferece suporte a várias sobreposições simultâneas.",
    "supportsCustomCursorStyle": "Permite usar arquivos enviados pelo usuário, pacotes gerados por habilidades ou outros recursos de cursor personalizados.",
    "supportsPresetImportExportSharing": "Permite exportar predefinições como arquivos locais visíveis no Finder e importar arquivos de predefinições.",
    "lifetimePrice": "Em dólares americanos. Deixe em branco se não estiver disponível."
  }
} as const satisfies Record<Exclude<Locale, 'en'>, Record<string, string>>;

export function localizedFieldDescription(locale: Locale, field: FieldDefinition): string | undefined {
  if (!field.description) return undefined;
  if (locale === 'en') return field.description;
  const translated: Readonly<Record<string, string>> = descriptions[locale];
  return translated[field.key] ?? field.description;
}
