'use client';

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import type { FieldDefinition, FieldGroup } from './recorders';

export const locales = ['en', 'zh-CN', 'zh-TW', 'ja', 'ko', 'es', 'fr', 'de', 'pt-BR'] as const;
export type Locale = typeof locales[number];

export const localeNames: Record<Locale, string> = {
  en: 'English', 'zh-CN': '简体中文', 'zh-TW': '繁體中文', ja: '日本語', ko: '한국어',
  es: 'Español', fr: 'Français', de: 'Deutsch', 'pt-BR': 'Português',
};

type Messages = Record<string, string>;
const en: Messages = {
  addRecorder:'Add a recorder', search:'Search recorders…', filters:'Filters', sort:'Sort', clear:'Clear', any:'Any', yes:'Yes', no:'No', unknown:'Unknown',
  addSort:'Add sort condition', noSort:'No sorting applied. Products keep their source order.', recorders:'{count} recorders', selectedRecorders:'Showing selected recorders', selectToCompare:'Select any number to compare', resetWeights:'Reset weights', weight:'Weight', score:'score', lastUpdated:'Last updated', version:'Version {version}', versionUnknown:'Version unknown', noMatches:'No recorders match those filters.', hideIdentical:'Hide identical', selected:'{count} selected', ready:'Ready to compare', exitComparison:'Exit comparison', compareSelected:'Compare selected',
  backToComparison:'Back to comparison', contribute:'Contribute data', addRecorderTitle:'Add a recorder.', submitIntro:'Fill in what you know. Nothing is submitted automatically—you’ll get a clean JSON object or a ready-to-send prompt.', productDetails:'Product details', pricesUsd:'All prices are in USD.', required:'Required', generatedOutput:'Generated output', copy:'Copy to clipboard', copied:'Copied', privacy:'Your data stays in this browser. Nothing is sent anywhere.',
  ask:'Ask about these recorders…', downloadAssistant:'Download the local assistant?', downloadDescription:'The first message needs a one-time download of {size}. The model is cached by your browser and conversations stay on this device.', notNow:'Not now', downloadAndSend:'Download and send', language:'Language', visitWebsite:'Visit {name} website', compareProduct:'Compare {name}',
};
const zhCN: Messages = {
  addRecorder:'添加录屏软件', search:'搜索录屏软件…', filters:'筛选', sort:'排序', clear:'清除', any:'任意', yes:'是', no:'否', unknown:'未知', addSort:'添加排序条件', noSort:'未设置排序，产品将保持原始顺序。', recorders:'{count} 款软件', selectedRecorders:'正在显示已选择的软件', selectToCompare:'可选择任意数量进行对比', resetWeights:'重置权重', weight:'权重', score:'得分', lastUpdated:'最后更新', version:'版本 {version}', versionUnknown:'版本未知', noMatches:'没有符合筛选条件的软件。', hideIdentical:'隐藏相同项', selected:'已选择 {count} 项', ready:'可以开始对比', exitComparison:'退出对比', compareSelected:'对比所选', backToComparison:'返回对比页', contribute:'贡献数据', addRecorderTitle:'添加录屏软件', submitIntro:'填写你了解的信息。页面不会自动提交，而是生成干净的 JSON 或可直接发送的 Prompt。', productDetails:'产品信息', pricesUsd:'所有价格均以美元计价。', required:'必填', generatedOutput:'生成结果', copy:'复制到剪贴板', copied:'已复制', privacy:'数据只保留在当前浏览器中，不会被发送。', ask:'询问这些录屏软件…', downloadAssistant:'下载本地助手？', downloadDescription:'首次发送消息需要下载一次约 {size} 的模型。模型会缓存在浏览器中，对话只保留在此设备。', notNow:'暂不', downloadAndSend:'下载并发送', language:'语言', visitWebsite:'访问 {name} 官网', compareProduct:'对比 {name}',
};
const zhTW: Messages = {
  addRecorder:'新增錄影軟體', search:'搜尋錄影軟體…', filters:'篩選', sort:'排序', clear:'清除', any:'任意', yes:'是', no:'否', unknown:'未知', addSort:'新增排序條件', noSort:'尚未套用排序，產品將維持原始順序。', recorders:'{count} 款軟體', selectedRecorders:'正在顯示已選軟體', selectToCompare:'可選擇任意數量進行比較', resetWeights:'重設權重', weight:'權重', score:'得分', lastUpdated:'最後更新', version:'版本 {version}', versionUnknown:'版本未知', noMatches:'沒有符合篩選條件的軟體。', hideIdentical:'隱藏相同項目', selected:'已選擇 {count} 項', ready:'可以開始比較', exitComparison:'離開比較', compareSelected:'比較所選', backToComparison:'返回比較頁', contribute:'貢獻資料', addRecorderTitle:'新增錄影軟體', submitIntro:'填寫你知道的資訊。頁面不會自動提交，而會產生乾淨的 JSON 或可直接傳送的 Prompt。', productDetails:'產品資訊', pricesUsd:'所有價格均以美元計價。', required:'必填', generatedOutput:'產生結果', copy:'複製到剪貼簿', copied:'已複製', privacy:'資料只保留在此瀏覽器，不會傳送出去。', ask:'詢問這些錄影軟體…', downloadAssistant:'下載本機助手？', downloadDescription:'首次傳送訊息需要下載一次約 {size} 的模型。模型會快取於瀏覽器，對話只保留在此裝置。', notNow:'暫不', downloadAndSend:'下載並傳送', language:'語言', visitWebsite:'造訪 {name} 官網', compareProduct:'比較 {name}',
};
const ja: Messages = { addRecorder:'レコーダーを追加',search:'レコーダーを検索…',filters:'フィルター',sort:'並べ替え',clear:'クリア',any:'すべて',yes:'はい',no:'いいえ',unknown:'不明',addSort:'並べ替え条件を追加',noSort:'並べ替えは適用されていません。',recorders:'{count} 件',selectedRecorders:'選択した製品を表示中',selectToCompare:'任意の数を選んで比較',resetWeights:'重みをリセット',weight:'重み',score:'スコア',lastUpdated:'最終更新',version:'バージョン {version}',versionUnknown:'バージョン不明',noMatches:'条件に一致する製品はありません。',hideIdentical:'同じ項目を隠す',selected:'{count} 件選択',ready:'比較できます',exitComparison:'比較を終了',compareSelected:'選択項目を比較',backToComparison:'比較に戻る',contribute:'データを提供',addRecorderTitle:'レコーダーを追加',submitIntro:'分かる範囲で入力してください。JSON またはプロンプトを生成します。',productDetails:'製品情報',pricesUsd:'価格はすべて米ドルです。',required:'必須',generatedOutput:'生成結果',copy:'クリップボードにコピー',copied:'コピー済み',privacy:'データはこのブラウザ内にのみ保存されます。',ask:'レコーダーについて質問…',downloadAssistant:'ローカルアシスタントをダウンロードしますか？',downloadDescription:'最初のメッセージには約 {size} のモデルを一度ダウンロードする必要があります。',notNow:'後で',downloadAndSend:'ダウンロードして送信',language:'言語',visitWebsite:'{name} の公式サイトを開く',compareProduct:'{name} を比較' };
const ko: Messages = { addRecorder:'레코더 추가',search:'레코더 검색…',filters:'필터',sort:'정렬',clear:'지우기',any:'전체',yes:'예',no:'아니요',unknown:'알 수 없음',addSort:'정렬 조건 추가',noSort:'정렬이 적용되지 않았습니다.',recorders:'레코더 {count}개',selectedRecorders:'선택한 레코더 표시 중',selectToCompare:'원하는 수만큼 선택해 비교',resetWeights:'가중치 초기화',weight:'가중치',score:'점수',lastUpdated:'마지막 업데이트',version:'버전 {version}',versionUnknown:'버전 알 수 없음',noMatches:'조건에 맞는 레코더가 없습니다.',hideIdentical:'동일 항목 숨기기',selected:'{count}개 선택',ready:'비교 준비 완료',exitComparison:'비교 종료',compareSelected:'선택 항목 비교',backToComparison:'비교로 돌아가기',contribute:'데이터 제공',addRecorderTitle:'레코더 추가',submitIntro:'아는 정보를 입력하면 JSON 또는 프롬프트를 생성합니다.',productDetails:'제품 정보',pricesUsd:'모든 가격은 USD입니다.',required:'필수',generatedOutput:'생성 결과',copy:'클립보드에 복사',copied:'복사됨',privacy:'데이터는 이 브라우저에만 저장됩니다.',ask:'레코더에 대해 질문…',downloadAssistant:'로컬 어시스턴트를 다운로드할까요?',downloadDescription:'첫 메시지에는 약 {size} 모델을 한 번 다운로드해야 합니다.',notNow:'나중에',downloadAndSend:'다운로드 후 전송',language:'언어',visitWebsite:'{name} 웹사이트 방문',compareProduct:'{name} 비교' };
const es: Messages = { addRecorder:'Añadir grabador',search:'Buscar grabadores…',filters:'Filtros',sort:'Ordenar',clear:'Limpiar',any:'Cualquiera',yes:'Sí',no:'No',unknown:'Desconocido',addSort:'Añadir criterio',noSort:'No hay orden aplicado.',recorders:'{count} grabadores',selectedRecorders:'Mostrando los seleccionados',selectToCompare:'Selecciona cualquier cantidad para comparar',resetWeights:'Restablecer pesos',weight:'Peso',score:'puntuación',lastUpdated:'Última actualización',version:'Versión {version}',versionUnknown:'Versión desconocida',noMatches:'Ningún grabador coincide con los filtros.',hideIdentical:'Ocultar iguales',selected:'{count} seleccionados',ready:'Listo para comparar',exitComparison:'Salir de comparación',compareSelected:'Comparar selección',backToComparison:'Volver a la comparación',contribute:'Aportar datos',addRecorderTitle:'Añadir un grabador',submitIntro:'Completa lo que sepas para generar JSON o un prompt.',productDetails:'Datos del producto',pricesUsd:'Todos los precios están en USD.',required:'Obligatorio',generatedOutput:'Resultado generado',copy:'Copiar al portapapeles',copied:'Copiado',privacy:'Tus datos permanecen en este navegador.',ask:'Pregunta sobre estos grabadores…',downloadAssistant:'¿Descargar el asistente local?',downloadDescription:'El primer mensaje requiere una descarga única de unos {size}.',notNow:'Ahora no',downloadAndSend:'Descargar y enviar',language:'Idioma',visitWebsite:'Visitar el sitio de {name}',compareProduct:'Comparar {name}' };
const fr: Messages = { addRecorder:'Ajouter un enregistreur',search:'Rechercher…',filters:'Filtres',sort:'Trier',clear:'Effacer',any:'Tous',yes:'Oui',no:'Non',unknown:'Inconnu',addSort:'Ajouter un tri',noSort:'Aucun tri appliqué.',recorders:'{count} enregistreurs',selectedRecorders:'Affichage de la sélection',selectToCompare:'Sélectionnez autant de produits que nécessaire',resetWeights:'Réinitialiser les poids',weight:'Poids',score:'score',lastUpdated:'Dernière mise à jour',version:'Version {version}',versionUnknown:'Version inconnue',noMatches:'Aucun produit ne correspond aux filtres.',hideIdentical:'Masquer les éléments identiques',selected:'{count} sélectionnés',ready:'Prêt à comparer',exitComparison:'Quitter la comparaison',compareSelected:'Comparer la sélection',backToComparison:'Retour à la comparaison',contribute:'Contribuer',addRecorderTitle:'Ajouter un enregistreur',submitIntro:'Renseignez ce que vous savez pour générer du JSON ou un prompt.',productDetails:'Informations produit',pricesUsd:'Tous les prix sont en USD.',required:'Obligatoire',generatedOutput:'Résultat généré',copy:'Copier',copied:'Copié',privacy:'Vos données restent dans ce navigateur.',ask:'Posez une question sur ces produits…',downloadAssistant:'Télécharger l’assistant local ?',downloadDescription:'Le premier message nécessite un téléchargement unique d’environ {size}.',notNow:'Pas maintenant',downloadAndSend:'Télécharger et envoyer',language:'Langue',visitWebsite:'Visiter le site de {name}',compareProduct:'Comparer {name}' };
const de: Messages = { addRecorder:'Recorder hinzufügen',search:'Recorder suchen…',filters:'Filter',sort:'Sortieren',clear:'Leeren',any:'Alle',yes:'Ja',no:'Nein',unknown:'Unbekannt',addSort:'Sortierung hinzufügen',noSort:'Keine Sortierung angewendet.',recorders:'{count} Recorder',selectedRecorders:'Ausgewählte Recorder werden angezeigt',selectToCompare:'Beliebig viele zum Vergleichen auswählen',resetWeights:'Gewichte zurücksetzen',weight:'Gewicht',score:'Punkte',lastUpdated:'Zuletzt aktualisiert',version:'Version {version}',versionUnknown:'Version unbekannt',noMatches:'Keine Recorder entsprechen den Filtern.',hideIdentical:'Gleiche ausblenden',selected:'{count} ausgewählt',ready:'Bereit zum Vergleichen',exitComparison:'Vergleich verlassen',compareSelected:'Auswahl vergleichen',backToComparison:'Zurück zum Vergleich',contribute:'Daten beitragen',addRecorderTitle:'Recorder hinzufügen',submitIntro:'Fülle aus, was du weißt, und erhalte JSON oder einen Prompt.',productDetails:'Produktdaten',pricesUsd:'Alle Preise in USD.',required:'Erforderlich',generatedOutput:'Generierte Ausgabe',copy:'Kopieren',copied:'Kopiert',privacy:'Deine Daten bleiben in diesem Browser.',ask:'Frage zu diesen Recordern…',downloadAssistant:'Lokalen Assistenten herunterladen?',downloadDescription:'Für die erste Nachricht ist ein einmaliger Download von etwa {size} erforderlich.',notNow:'Nicht jetzt',downloadAndSend:'Herunterladen und senden',language:'Sprache',visitWebsite:'Website von {name} besuchen',compareProduct:'{name} vergleichen' };
const ptBR: Messages = { addRecorder:'Adicionar gravador',search:'Buscar gravadores…',filters:'Filtros',sort:'Ordenar',clear:'Limpar',any:'Qualquer',yes:'Sim',no:'Não',unknown:'Desconhecido',addSort:'Adicionar ordenação',noSort:'Nenhuma ordenação aplicada.',recorders:'{count} gravadores',selectedRecorders:'Mostrando os selecionados',selectToCompare:'Selecione qualquer quantidade para comparar',resetWeights:'Redefinir pesos',weight:'Peso',score:'pontuação',lastUpdated:'Última atualização',version:'Versão {version}',versionUnknown:'Versão desconhecida',noMatches:'Nenhum gravador corresponde aos filtros.',hideIdentical:'Ocultar iguais',selected:'{count} selecionados',ready:'Pronto para comparar',exitComparison:'Sair da comparação',compareSelected:'Comparar selecionados',backToComparison:'Voltar à comparação',contribute:'Contribuir com dados',addRecorderTitle:'Adicionar gravador',submitIntro:'Preencha o que souber para gerar JSON ou um prompt.',productDetails:'Dados do produto',pricesUsd:'Todos os preços estão em USD.',required:'Obrigatório',generatedOutput:'Resultado gerado',copy:'Copiar',copied:'Copiado',privacy:'Seus dados ficam neste navegador.',ask:'Pergunte sobre estes gravadores…',downloadAssistant:'Baixar o assistente local?',downloadDescription:'A primeira mensagem requer um download único de cerca de {size}.',notNow:'Agora não',downloadAndSend:'Baixar e enviar',language:'Idioma',visitWebsite:'Visitar o site de {name}',compareProduct:'Comparar {name}' };

const messages: Record<Locale, Messages> = { en, 'zh-CN':zhCN, 'zh-TW':zhTW, ja, ko, es, fr, de, 'pt-BR':ptBR };

const groupNames: Partial<Record<Locale, Record<string,string>>> = {
  'zh-CN': {general:'通用',pricing:'价格',screenshots:'截图',zoomEffects:'缩放效果',dynamicBlur:'运动模糊',animationAdjustments:'动画调整',camera3d:'3D 运镜',recording:'录制',microphoneRecording:'麦克风录制',systemAudioRecording:'系统音频录制',cameraRecording:'相机录制',customBackgrounds:'自定义背景',pictureAdjustments:'画面调整',deviceFrames:'设备套壳',annotations:'标注',cursor:'光标',transcription:'字幕与转录',backgroundMusic:'背景音乐',keystrokes:'按键',exportSharing:'导出与分享',presets:'预设'},
  'zh-TW': {general:'一般',pricing:'價格',screenshots:'截圖',zoomEffects:'縮放效果',dynamicBlur:'動態模糊',animationAdjustments:'動畫調整',camera3d:'3D 運鏡',recording:'錄製',microphoneRecording:'麥克風錄製',systemAudioRecording:'系統音訊錄製',cameraRecording:'相機錄製',customBackgrounds:'自訂背景',pictureAdjustments:'畫面調整',deviceFrames:'裝置外框',annotations:'標註',cursor:'游標',transcription:'字幕與轉錄',backgroundMusic:'背景音樂',keystrokes:'按鍵',exportSharing:'匯出與分享',presets:'預設'},
  ja:{general:'一般',pricing:'価格',screenshots:'スクリーンショット',zoomEffects:'ズーム効果',dynamicBlur:'モーションブラー',animationAdjustments:'アニメーション調整',camera3d:'3D カメラ',recording:'録画',microphoneRecording:'マイク録音',systemAudioRecording:'システム音声',cameraRecording:'カメラ録画',customBackgrounds:'カスタム背景',pictureAdjustments:'画面調整',deviceFrames:'デバイスフレーム',annotations:'注釈',cursor:'カーソル',transcription:'字幕と文字起こし',backgroundMusic:'BGM',keystrokes:'キー操作',exportSharing:'書き出しと共有',presets:'プリセット'},
  ko:{general:'일반',pricing:'가격',screenshots:'스크린샷',zoomEffects:'줌 효과',dynamicBlur:'모션 블러',animationAdjustments:'애니메이션 조정',camera3d:'3D 카메라',recording:'녹화',microphoneRecording:'마이크 녹음',systemAudioRecording:'시스템 오디오',cameraRecording:'카메라 녹화',customBackgrounds:'사용자 지정 배경',pictureAdjustments:'화면 조정',deviceFrames:'기기 프레임',annotations:'주석',cursor:'커서',transcription:'자막 및 전사',backgroundMusic:'배경 음악',keystrokes:'키 입력',exportSharing:'내보내기 및 공유',presets:'프리셋'},
  es:{general:'General',pricing:'Precios',screenshots:'Capturas',zoomEffects:'Efectos de zoom',recording:'Grabación',customBackgrounds:'Fondos personalizados',pictureAdjustments:'Ajustes de imagen',deviceFrames:'Marcos de dispositivo',annotations:'Anotaciones',cursor:'Cursor',transcription:'Subtítulos y transcripción',backgroundMusic:'Música de fondo',keystrokes:'Teclas',exportSharing:'Exportar y compartir',presets:'Preajustes'},
  fr:{general:'Général',pricing:'Tarifs',screenshots:'Captures',zoomEffects:'Effets de zoom',recording:'Enregistrement',customBackgrounds:'Arrière-plans',pictureAdjustments:'Réglages d’image',deviceFrames:'Cadres d’appareil',annotations:'Annotations',cursor:'Curseur',transcription:'Sous-titres et transcription',backgroundMusic:'Musique',keystrokes:'Touches',exportSharing:'Export et partage',presets:'Préréglages'},
  de:{general:'Allgemein',pricing:'Preise',screenshots:'Screenshots',zoomEffects:'Zoom-Effekte',recording:'Aufnahme',customBackgrounds:'Eigene Hintergründe',pictureAdjustments:'Bildanpassungen',deviceFrames:'Geräterahmen',annotations:'Anmerkungen',cursor:'Cursor',transcription:'Untertitel & Transkription',backgroundMusic:'Hintergrundmusik',keystrokes:'Tasten',exportSharing:'Export & Teilen',presets:'Voreinstellungen'},
  'pt-BR':{general:'Geral',pricing:'Preços',screenshots:'Capturas',zoomEffects:'Efeitos de zoom',recording:'Gravação',customBackgrounds:'Fundos personalizados',pictureAdjustments:'Ajustes de imagem',deviceFrames:'Molduras de dispositivo',annotations:'Anotações',cursor:'Cursor',transcription:'Legendas e transcrição',backgroundMusic:'Música de fundo',keystrokes:'Teclas',exportSharing:'Exportar e compartilhar',presets:'Predefinições'},
};

const fieldNames: Partial<Record<Locale, Record<string,string>>> = {
  'zh-CN': {name:'产品名称',website:'官网',score:'得分',lastUpdatedAt:'最后更新时间',lastUpdatedVersion:'应用版本',technologyApproach:'技术方案',platforms:'平台',supportsIntelMac:'支持 Intel 芯片 Mac',appSizeMB:'应用体积',requiresRegistration:'需要注册',availableOnMacAppStore:'上架 Mac App Store',isOpenSource:'是否开源',monthlyPrice:'月付价格',quarterlyPrice:'季付价格',yearlyPrice:'年付价格',lifetimePrice:'买断价格',supportsScreenshots:'窗口截图支持',supportsScrollingScreenshots:'滚动截图',supportsCopyText:'复制文字',supportsBasicAnnotations:'基础标注',supportsCustomBackgrounds:'是否支持',supportsCustomCorners:'自定义圆角',supportsCustomShadows:'自定义阴影',supports3DEffects:'3D 效果',supportsDeviceFrames:'是否支持',supportsResolutionControls:'分辨率和清晰度调整',supportsDynamicBlurControls:'是否支持',supports3DCameraMovement:'是否支持',supportsCurveControls:'曲线调整',supportsSpeedControls:'速度调整',supportsDepthOfField:'景深效果',supportsDepthStrengthControls:'景深强度调节',supportsScreenReflection:'屏幕反光模拟',camera3DControlMethod:'3D 调节方式',zoomLimit:'缩放上限',supportsWindowRecordingMode:'窗口模式',supportsTextCursorTracking:'跟踪文本光标',supportsKeystrokeRecording:'按键录制',supportsIPhoneRecording:'iPhone 录制',supportsAndroidRecording:'Android 录制',supportsMicrophoneRecording:'是否支持',supportsMicrophoneNoiseReduction:'降噪',supportsMicrophoneMultitrack:'多音轨录制',supportsSystemAudioRecording:'是否支持',supportsSystemAudioMultitrack:'多音轨',supportsCameraBeauty:'美颜',supportsCameraBackgroundRemoval:'背景移除',supportsCameraBackgroundReplacement:'背景替换',supportsTeleprompter:'提词器',supportsWallpaperBackground:'壁纸',supportsColorBackground:'颜色',supportsGradientBackground:'渐变',supportsVideoBackground:'视频',supportsCustomImageBackground:'自定义图片',supportsCustomVideoBackground:'自定义视频',supportsAspectRatioAdjustment:'比例调整',supportsCropping:'裁剪',supportsSmoothCorners:'平滑圆角',supportsMosaic:'马赛克',supportsTextAnnotations:'文字',supportsFocusEffect:'聚焦效果',supportsAnnotationOverlay:'支持叠加',supportsCursorToggle:'光标开关',supportsCursorAutoHide:'静止时隐藏',supportsCursorStyleReplacement:'更换光标样式',supportsCustomCursorStyle:'自定义光标样式',supportsClickSounds:'点击音效',supportsSeparatePressReleaseSounds:'区分按下和释放音效',supportsClickEffects:'点击效果',supportsTranscription:'支持转录',transcriptionProviders:'转录服务',supportsSubtitleEditing:'字幕编辑',supportsWordLevelEditing:'逐字编辑',subtitleOutputType:'字幕类型',supportsBackgroundMusic:'是否支持',supportsOfficialMusic:'官方素材',supportsLocalMusic:'本地素材',supportsMusicEditing:'剪辑和拼接',supportsMusicFade:'淡入/淡出',supportsAllKeyRecording:'录制所有按键',supportsShortcutRecording:'录制快捷键',supportsKeyStyleAdjustment:'按键样式调整',supportsKeyPositionAdjustment:'按键位置调整',supportsVideoExport:'视频导出',supportsTransparentMovExport:'透明背景 MOV 导出',supportsGifExport:'GIF 导出',supportsLivePhotoExport:'Live Photo 导出',supportsExportResolutionSelection:'分辨率选择',supportsExportQualitySelection:'清晰度选择',supportsExportFrameRateSelection:'刷新率选择',supportsExportSizeEstimate:'导出尺寸预估',supportsExportDurationEstimate:'导出时长预估',supportsShareLinks:'分享链接',supportsPresets:'是否支持',supportsPresetImportExportSharing:'导入/导出/分享'},
  'zh-TW': {name:'產品名稱',website:'官網',score:'得分',lastUpdatedAt:'最後更新日期',lastUpdatedVersion:'應用程式版本',technologyApproach:'技術方案',platforms:'平台',supportsIntelMac:'支援 Intel 晶片 Mac',appSizeMB:'應用程式大小',requiresRegistration:'需要註冊',availableOnMacAppStore:'上架 Mac App Store',isOpenSource:'是否開源',monthlyPrice:'月費',quarterlyPrice:'季費',yearlyPrice:'年費',lifetimePrice:'買斷價格',supportsScreenshots:'視窗截圖支援',supportsScrollingScreenshots:'捲動截圖',supportsCopyText:'複製文字',supportsTeleprompter:'提詞器'},
  ja:{name:'製品名',website:'公式サイト',score:'スコア',lastUpdatedAt:'最終更新日',lastUpdatedVersion:'アプリバージョン',technologyApproach:'技術方式',platforms:'対応OS',supportsIntelMac:'Intel Mac 対応',appSizeMB:'アプリサイズ',requiresRegistration:'登録が必要',availableOnMacAppStore:'Mac App Store',isOpenSource:'オープンソース',monthlyPrice:'月額',quarterlyPrice:'四半期価格',yearlyPrice:'年額',lifetimePrice:'買い切り価格',supportsScreenshots:'ウィンドウ撮影',supportsScrollingScreenshots:'スクロール撮影',supportsCopyText:'テキストコピー'},
  ko:{name:'제품명',website:'공식 웹사이트',score:'점수',lastUpdatedAt:'마지막 업데이트',lastUpdatedVersion:'앱 버전',technologyApproach:'기술 방식',platforms:'플랫폼',supportsIntelMac:'Intel Mac 지원',appSizeMB:'앱 크기',requiresRegistration:'가입 필요',availableOnMacAppStore:'Mac App Store 등록',isOpenSource:'오픈 소스',monthlyPrice:'월 가격',quarterlyPrice:'분기 가격',yearlyPrice:'연간 가격',lifetimePrice:'영구 가격'},
  es:{name:'Nombre del producto',website:'Sitio oficial',score:'Puntuación',lastUpdatedAt:'Última actualización',lastUpdatedVersion:'Versión',technologyApproach:'Tecnología',platforms:'Plataformas',supportsIntelMac:'Compatible con Mac Intel',appSizeMB:'Tamaño',requiresRegistration:'Requiere registro',availableOnMacAppStore:'Disponible en Mac App Store',isOpenSource:'Código abierto',monthlyPrice:'Precio mensual',quarterlyPrice:'Precio trimestral',yearlyPrice:'Precio anual',lifetimePrice:'Precio perpetuo'},
  fr:{name:'Nom du produit',website:'Site officiel',score:'Score',lastUpdatedAt:'Dernière mise à jour',lastUpdatedVersion:'Version',technologyApproach:'Technologie',platforms:'Plateformes',supportsIntelMac:'Compatible avec les Mac Intel',appSizeMB:'Taille',requiresRegistration:'Inscription requise',availableOnMacAppStore:'Disponible sur le Mac App Store',isOpenSource:'Open source',monthlyPrice:'Prix mensuel',quarterlyPrice:'Prix trimestriel',yearlyPrice:'Prix annuel',lifetimePrice:'Prix à vie'},
  de:{name:'Produktname',website:'Offizielle Website',score:'Punkte',lastUpdatedAt:'Zuletzt aktualisiert',lastUpdatedVersion:'App-Version',technologyApproach:'Technologie',platforms:'Plattformen',supportsIntelMac:'Intel-Mac-Unterstützung',appSizeMB:'App-Größe',requiresRegistration:'Registrierung erforderlich',availableOnMacAppStore:'Im Mac App Store',isOpenSource:'Open Source',monthlyPrice:'Monatspreis',quarterlyPrice:'Quartalspreis',yearlyPrice:'Jahrespreis',lifetimePrice:'Einmalpreis'},
  'pt-BR':{name:'Nome do produto',website:'Site oficial',score:'Pontuação',lastUpdatedAt:'Última atualização',lastUpdatedVersion:'Versão',technologyApproach:'Tecnologia',platforms:'Plataformas',supportsIntelMac:'Compatível com Mac Intel',appSizeMB:'Tamanho',requiresRegistration:'Requer cadastro',availableOnMacAppStore:'Disponível na Mac App Store',isOpenSource:'Código aberto',monthlyPrice:'Preço mensal',quarterlyPrice:'Preço trimestral',yearlyPrice:'Preço anual',lifetimePrice:'Preço vitalício'},
};

const performanceGroupNames: Partial<Record<Locale, Record<string,string>>> = {
  'zh-CN': {performance:'性能',performanceRecording:'录制',performanceRecordingCPU:'CPU',performanceRecordingMemory:'内存',performancePreview:'回放',performancePreviewCPU:'CPU',performancePreviewMemory:'内存',performanceExport:'导出',performanceExportCPU:'CPU',performanceExportMemory:'内存'},
  'zh-TW': {performance:'效能',performanceRecording:'錄製',performanceRecordingCPU:'CPU',performanceRecordingMemory:'記憶體',performancePreview:'回放',performancePreviewCPU:'CPU',performancePreviewMemory:'記憶體',performanceExport:'匯出',performanceExportCPU:'CPU',performanceExportMemory:'記憶體'},
};

const performanceFieldNames: Partial<Record<Locale, Record<string,string>>> = {
  'zh-CN': {Average:'平均',Peak:'最高',Time:'时间'},
  'zh-TW': {Average:'平均',Peak:'最高',Time:'時間'},
};

const normalizeLocale = (value: string | null | undefined): Locale => {
  if (!value) return 'en';
  const exact = locales.find((locale) => locale.toLowerCase() === value.toLowerCase());
  if (exact) return exact;
  const language = value.toLowerCase();
  if (language.startsWith('zh')) return language.includes('tw') || language.includes('hk') || language.includes('hant') ? 'zh-TW' : 'zh-CN';
  return locales.find((locale) => locale.split('-')[0] === language.split('-')[0]) ?? 'en';
};

type I18nContextValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: string, vars?: Record<string,string|number>) => string; fieldLabel: (field: FieldDefinition) => string; groupLabel: (group: FieldGroup) => string; optionLabel: (option: {value:string;label:string}) => string };
const I18nContext = createContext<I18nContextValue | null>(null);
const interpolate = (text: string, vars?: Record<string,string|number>) => Object.entries(vars ?? {}).reduce((result,[key,value]) => result.replaceAll(`{${key}}`,String(value)),text);

export function I18nProvider({children}:{children:ReactNode}) {
  const [locale,setLocaleState] = useState<Locale>('en');
  useEffect(() => { setLocaleState(normalizeLocale(localStorage.getItem('recorder-locale') || navigator.language)); }, []);
  const setLocale = (next: Locale) => { setLocaleState(next); localStorage.setItem('recorder-locale',next); };
  useEffect(() => { document.documentElement.lang=locale; },[locale]);
  const value = useMemo<I18nContextValue>(() => ({
    locale, setLocale,
    t:(key,vars)=>interpolate(messages[locale][key] ?? en[key] ?? key,vars),
    fieldLabel:(field)=>fieldNames[locale]?.[field.key] ?? performanceFieldNames[locale]?.[field.label] ?? field.label,
    groupLabel:(group)=>performanceGroupNames[locale]?.[group.key] ?? groupNames[locale]?.[group.key] ?? group.label,
    optionLabel:(option)=>option.label,
  }),[locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export const useI18n = () => {
  const value = useContext(I18nContext);
  if (!value) throw new Error('useI18n must be used inside I18nProvider');
  return value;
};
